baseURL = 'https://sanderfrenken.github.io/'
languageCode = 'en-us'
title = 'iGameDev'
theme = 'gokarna'
enableEmoji = true

[params]
  footer = "Sander Frenken"
  description = "Everything about my journey as a game developer"
  avatarURL = "https://sanderfrenken.github.io/dev-blog/static/icon.png"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  ShowBackToTopButton = true
  showPostsOnHomePage = "recent"

  socialIcons = [
    {name = "reddit", url = "https://www.reddit.com/user/sanderfrenken/"},
    {name = "discord", url = "https://discord.gg/SKDS5VK2"},
    {name = "linkedin", url = "https://nl.linkedin.com/in/sander-frenken-071a2157"},
    {name = "email", url = "mailto:rednasgamesinfo@gmail.com"}
  ]
  metaKeywords = ["blog", "spritekit", "game developer"]

  [menu]
    [[menu.main]]
      name = "Home"
      pre = "<span data-feather='home'></span>"
      url = "/"
      weight = 1
    [[menu.main]]
      name = "Posts"
      pre = "<span data-feather='book'></span>"
      url = "/posts/"      
      weight = 2
    [[menu.main]]
      name = "Projects"
      pre = "<span data-feather='code'></span>"
      url = "/projects/"
      weight = 3
    [[menu.main]]
      identifier = "github"
      pre = "<span data-feather='github'></span>"
      url = "https://github.com/sanderfrenken"
      weight = 4
    [[menu.main]]
      identifier = "me"
      pre = "<span data-feather='smile'></span>"
      url = "/posts/welcome"
      weight = 4
